cursor #f0dede
cursor_text_color #d7c1c2

foreground            #f0dede
background            #1a1112
selection_foreground  #44292b
selection_background  #e6bdbe
url_color             #ffb2b7

color0   #1a1112
color1   #ff7273
color2   #9cff7f
color3   #ffe372
color4   #f29aa0
color5   #763438
color6   #ffb2b7
color7   #ffeff0
color8   #494041
color9   #ff9fa0
color10  #b9ffa5
color11  #ffeda5
color12  #ffbdc1
color13  #ffc9cc
color14  #ffdcde
color15  #fff8f9
