cursor #f5dce3
cursor_text_color #d8c1c7

foreground            #f5dce3
background            #1c1015
selection_foreground  #4b252d
selection_background  #f2b7c1
url_color             #ffb0cf

color0   #1c1015
color1   #ff7279
color2   #a0ff7f
color3   #ffe172
color4   #f298bb
color5   #76324d
color6   #ffb0cf
color7   #ffeff5
color8   #a5999e
color9   #ff9fa3
color10  #bcffa5
color11  #ffeca5
color12  #ffbbd6
color13  #ffc7dd
color14  #ffdbe9
color15  #fff8fb
