[mgr]
# spacing
ratio = [1, 4, 3]

# sorting
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false

linemode = "none" 
# other preferred options "permissions", "owner", "size"

show_hidden = false
show_symlink = true

title_format = "JetBrainsMono Nerd Font"


[preview]
wrap = "yes"
image_quality = 90
