add_newline = false

format = """
[](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$python\
$nodejs\
[](fg:#86BBD8 bg:#06969A)\
$time\
[](fg:#06969A)\
$line_break$character
"""

[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[ $user ]($style)'
disabled = false

[directory]
#style = "bg:#DA627D"
#format = "[ $path ]($style)"
#truncation_length = 3
#truncation_symbol = "…/"
truncation_length = 2
truncation_symbol = "…/"
style = "bg:#DA627D"
format = "[ $path ]($style)"

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[c]
format = "[C]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#06969A"
format = '[  $time ]($style)'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
