-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "eDP-1", mode = "1366x768@59.999", position = "0x0", scale = 1, vrr = 0, mirror = "HDMI-A-1" })
hl.monitor({ output = "HDMI-A-1", mode = "3840x2160@30.000", position = "1366x0", scale = 1, vrr = 0 })
